name: Heroku Deployment

on:
  push:
    branches:
      - toCheck

jobs:
  deploy:
    name: Heroku Deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "home-rpg" #Must be unique in Heroku
          heroku_email: "xbrax27@gmail.com"
          branch: HEAD
          dontuseforce: false
          usedocker: false
          docker_heroku_process_type: web
          delay: 0
          rollbackonhealthcheckfailed: false
          justlogin: false